# Generated by Django 6.0.1 on 2026-01-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_elo',
            field=models.FloatField(default=1200),
        ),
    ]
